application:
  image: symfony/code
  volumes:
    - .:/var/www/symfony
  tty: true

db:
  image: mysql
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: mysqlroot
    MYSQL_DATABASE: symfony
    MYSQL_USER: admin
    MYSQL_PASSWORD: root

php:
  image: symfony/php-fpm
  expose:
    - 9000:9000
  volumes_from:
    - application
  links:
    - db
  
nginx:
  image: symfony/nginx
  ports:
    - 80:80
  links:
    - php
  volumes_from:
    - application
  volumes:
    - logs/nginx/:/var/log/nginx
